version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
  api:
    build: ./packages/backend
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/contractor
    depends_on:
      - mongo
    ports:
      - '4000:4000'
  ui:
    build: ./packages/frontend
    restart: always
    depends_on:
      - api
    ports:
      - '3000:80'
volumes:
  mongo-data:
